### ISSUE TITLE
Option to skip writing version file

### ISSUE THREAD

**Issue by jreese** [omnilib/attribution#2]
### Description

Currently, running `attribution tag` will not only create tags and update changelog, but also write a `__version__.py` in the project namespace.  This is redundant for projects already using something like `setuptools_scm` to manage version info, so an option to disable this is desired.

The option to disable this should be something like:

pyproject.toml
```
[tool.attribution]
version_file = false
```

Set a default value of `True` for this in `attribution.Project.load()`, then around `attribution/main.py:73`, this value can be retrieved from `Project.config` and used to determine if the version file should be written or skipped.

**Comment by markrofail** [comment]
would like to work on this
